# Generated by Django 6.1 on 2026-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessOs', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_date',
            field=models.DateField(db_index=True),
        ),
    ]
